version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - daaiki
  assignees:
    - daaiki
  commit-message:
    prefix: 'fix :bug:'
    prefix-development: 'chore :teddy_bear:'
